id: P007029
initial_creation_type: ocr
created_at: 29/03/2020
last_modified_at: 25/11/2021
source_metadata:
  id: bdr:W12419
  title: དབྱངས་ཅན་སྒྲ་མདོའི་རྩ་འགྲེལ་དང་མཚམས་སྦྱོར་ལྔ་པ་སོགས། ༼ཞོལ་པར་མ།༽
  author: ''
  volumes:
    fea32a26e11145869501b3a8e1d979f0:
      image_group_id: I1KG10762
      title: Volume 1 of dbyangs can sgra mdo'i rtsa 'grel dang mtshams sbyor lnga
        pa sogs/ (zhol par ma/)
      volume_number: 1
      total_pages: 496
      base_file: v001.txt
