id: P007029
initial_creation_type: ocr
source_metadata:
  id: bdr:W12419
  title: དབྱངས་ཅན་སྒྲ་མདོའི་རྩ་འགྲེལ་དང་མཚམས་སྦྱོར་ལྔ་པ་སོགས། ༼ཞོལ་པར་མ།༽
  author: ''
  volumes:
    c9522148326748058c73c0962fa9746a:
      image_group_id: I1KG10762
      title: ''
      volume_number: 1
      total_pages: 496
ebook_metadata:
  title: དབྱངས་ཅན་སྒྲ་མདོའི་རྩ་འགྲེལ་དང་མཚམས་སྦྱོར་ལྔ་པ་སོགས། ༼ཞོལ་པར་མ།༽
  author: ''
  sku: P007029
  cover: cover.jpg
  layers:
  - pagination
