id: I03B05303
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-29T23:50:09+00:00'
last_modified: '2022-06-08T13:23:08.515137+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W12419
  title: དབྱངས་ཅན་སྒྲ་མདོའི་རྩ་འགྲེལ་དང་མཚམས་སྦྱོར་ལྔ་པ་སོགས། ༼ཞོལ་པར་མ།༽
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    666D:
      image_group_id: I1KG10762
      title: Volume 1 of dbyangs can sgra mdo'i rtsa 'grel dang mtshams sbyor lnga
        pa sogs/ (zhol par ma/)
      total_pages: 496
      order: 1
      base_file: 666D.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
